services:
  - type: web
    name: zodiac-bot
    runtime: node
    plan: free
    region: oregon
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: CLIENT_ID
        value: "1549546723771416666"
      - key: GUILD_ID
        value: "1549028696512405594"
      - key: TIMEZONE
        value: "Asia/Dhaka"
      - key: PORT
        value: "3000"
